---
swagger: "2.0"
info:
  description: "APIs published for demo CRUD operations"
  version: "1.0.0"
  title: "Demo"
host: "localhost:8081"
basePath: "/resources"
tags:
- name: "resource"
schemes:
- "http"
- "https"
paths:
  /resource:
    get:
      tags:
      - "resource"
      summary: "Get user"
      description: "This can only be done by the logged in user."
      operationId: "get"
      parameters:
      - name: "X-Test"
        in: "header"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
