---
swagger: "2.0"
info:
  description: "APIs published for user CRUD operations"
  version: "1.0.0"
  title: "Demo"
host: "localhost:8080"
basePath: "/resources"
tags:
- name: "users"
schemes:
- "http"
paths:
  /users:
    get:
      tags:
      - "users"
      summary: "Get all users"
      description: "This can only be done by the logged in user."
      operationId: "getAll"
      parameters: []
      responses:
        400:
          description: "Invalid input"
        404:
          description: "User not found"
